services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://190.146.2.119:2345/postgres"
      SPRING_DATASOURCE_USERNAME: "grupo22_user"
      SPRING_DATASOURCE_PASSWORD: "G22#Px6!Rt2$Lm8@Qw9K"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
    restart: always