services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      #MAILTRAP_API_TOKEN: ${MAILTRAP_API_TOKEN}
      #MAILTRAP_INBOX_ID: ${MAILTRAP_INBOX_ID}
    restart: always