spring.application.name=backend

# MailTrap
mailtrap.inbox=******
mailtrap.token=******

# PostgreSQL
spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/grupo22
spring.datasource.username=grupo22_user
spring.datasource.password=******
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# PUERTO
server.port=8081