spring.application.name=backend

# MailTrap
mailtrap.inbox=4516053
mailtrap.token=fbd1f46bb864be854032ea5ef02d5464

# PostgreSQL
spring.datasource.url=jdbc:postgresql://190.146.2.119:2345/grupo22
spring.datasource.username=grupo22_user
spring.datasource.password=G22#Px6!Rt2$Lm8@Qw9K
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# PUERTO
server.port=8080